env:
  data_path: data/
  artifacts_path: artifacts/
  model_name: ImageClassifier
  training_split: 0.8
  epochs: 10
  batch_size: 64
  gpu: 0
  bucket: None

commands:
  - train:
    - python src/train.py
  - export:
    - python src/compile.py
  - data-load:
    - python src/data_load.py
    
#tasks:
#  - validate-data:
#    - python src/validate_data.py
