env:
  data_path: data/
  artifacts_path: artifacts/
  data_src: None
  model_name: ImageClassifier
  training_split: 0.8
  epochs: 10
  batch_size: 64
  gpu: 0

commands:
  - train:
    - python src/train.py
  - export:
    - python src/export.py
  - data-load:
    - python src/data_load.py

tasks:
  - data-clean:
    - python src/data_clean.py
